# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9270790760699942e59ae4c0c39d24304563a9b77a0e09ccc530af98aced8cf8120b0fbee90d4b4573e26cf734e8a2c7c6cc62c4af372d3d52aa04e0711c9e3c

test:
  secret_key_base: c149cbe93a40df9d86a841ae58ab5f8ae79aa015f66587cfa6a64b2103b2afc020c3611a019bc709732be6f942e52493f2f713091d0007400cc846f082635732

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
